### ISSUE TITLE
Character Count

### ISSUE THREAD

**Issue by Grandclosing** [Dobiasd/articles#11]
XD Ugh, not to be _that_ guy but...  
For functional_programming_in_cpp_with_the_functionalplus_library_today_hackerrank_challange_gemstones.md

Lorem ipsum
dolor sit amet,
consectetur,
adipisci velit

The characters of the character counts are: e and s

**Comment by Dobiasd** [comment]
Thank you very much. I [just fixed it](https://github.com/Dobiasd/articles/commit/c0e08ba700b8159d66c0bbad289f1fca81893a43).

(And in my notification email I see what you wrote before you edited your comment. :D)
