### ISSUE TITLE
404: What is Functional Reactive Programming?

### ISSUE THREAD

**Issue by comfytoday** [Dobiasd/articles#12]
http://elm-lang.org/learn/What-is-FRP.elm
:(

**Comment by Dobiasd** [comment]
Thanks for the remark. [Elm no longer uses FRP](http://elm-lang.org/blog/farewell-to-frp), but I made the link point to [an archive.org snapshot](https://web.archive.org/web/20141004072658/http://elm-lang.org/learn/What-is-FRP.elm) with this [commit](https://github.com/Dobiasd/articles/commit/eb172cd81d1a99c13fd6de43e0f03d8e8712f1f0).
