### ISSUE TITLE
"Self-assessment" in learning curves is less than wholly clear

### ISSUE THREAD

**Issue by aaron-em** [Dobiasd/articles#4]
English, at least as she is in America spoke, generally uses the term "self-assessment" to refer to what is at least intended to be a relatively objective analysis of one's capabilities, which is often produced in the context of employment, eventually written down on paper, and retained in an employee's permanent file.

Having twice now read your learning-curves article, I tend to suspect that the quality which, in the charts, you name "self-assessment", might more fluently in English be named something like "self-opinion", or perhaps ideally "self-regard"; this would, I think, make a lot of the charts easier on first reading to understand. (For example, interpreting in this fashion your PHP chart, one might gather that PHP programmers have an unjustifiably high regard for themselves, which would most in line with your intent seem to be.)

**Comment by maricn** [comment]
@Dobiasd It's pretty ambiguous for me (though, I'm not a native English speaker) - Do I assess myself more, or do I value myself more via the process of self-assessment :grey_question:
